apiVersion: v1
kind: Service
metadata:
  name: students-getbyid-service
spec:
  selector:
    app: students-getbyid-service
  ports:
    - protocol: TCP
      port: 8083
      nodePort: 30083
      targetPort: 8083
  type: NodePort 